ALTER TABLE BETTING_GROUP_PLAYERS DROP CONSTRAINT IF EXISTS BETTING_GROUP_PLAYERS_PLAYER_ID_FKEY;
ALTER TABLE BETTING_GROUP_PLAYERS DROP CONSTRAINT IF EXISTS BETTING_GROUP_PLAYERS_PKEY;
DROP TABLE IF EXISTS BETTING_GROUP_PLAYERS;
ALTER TABLE BETTING_GROUPS ADD COLUMN players text;
